### ISSUE TITLE
JWT ???

### ISSUE THREAD

**Issue by nakinthorn** [lnmarkets/docs#5]
i read your doc api and not found how to generate JWT for header Auth
<img width="1288" alt="Screen Shot 2564-02-03 at 13 53 46" src="https://user-images.githubusercontent.com/19216345/106709520-427a4880-6627-11eb-8bf4-70f6243fe335.png">

pls told me where in your doc to descript about how to generate jwt for use your api,

**Comment by nakinthorn** [comment]
<img width="1226" alt="Screen Shot 2564-02-03 at 13 56 35" src="https://user-images.githubusercontent.com/19216345/106709836-a69d0c80-6627-11eb-856e-c0a6335bd772.png">
i found it!!! it on your site

**Comment by vafanassieff** [comment]
Hey @nakinthorn sorry if it's not clear i will update the doc !
